version: '3.7'

services:
  bot:
    build: .
    image: wiibleyde/capsulebot:latest
    container_name: capsulebot
    restart: always
    volumes:
      - config.yml:./config.yml
      - data/:/var/capsule/data/
    environment:
      - TZ=Europe/Paris