version: '3.7'

services:
  bot:
    build: .
    image: wiibleyde/capsulebot:latest
    container_name: capsulebot
    restart: always
    volumes:
      - /var/capsule/config.yml:/app/config.yml
      - /var/capsule/data/:/app/data/
    environment:
      - TZ=Europe/Paris